// Code generated by gen-extensions; DO NOT EDIT.
//go:generate go run ../../../cmd/gen-extensions

// Package registriesall imports all registry connector extensions so their init() registrations run.
//
// To add a new extension of this kind:
//   1. Create a directory under extensions/registries/<name>/ with a .go file containing init() registration.
//   2. Run: go generate ./extensions/...
//   3. The new extension is automatically picked up on next build.
package registriesall

// No extensions found in extensions/registries. Add one to get started.
