// Code generated by gen-extensions; DO NOT EDIT.
//go:generate go run ../../../cmd/gen-extensions

// Package providersall imports all provider extensions so their init() registrations run.
//
// To add a new extension of this kind:
//   1. Create a directory under extensions/providers/<name>/ with a .go file containing init() registration.
//   2. Run: go generate ./extensions/...
//   3. The new extension is automatically picked up on next build.
package providersall

import (
	_ "github.com/yeeth-security/scintx/internal/scintx" // ensure registry is loaded
	_ "github.com/yeeth-security/scintx/extensions/providers/stub-osv"
	_ "github.com/yeeth-security/scintx/extensions/providers/stub-secrets"
)
