// Command gen-extensions scans the extensions/ directory and regenerates
// the all.go aggregation files that import every extension package,
// triggering their init() registration.
//
// Usage:
//
//	go generate ./extensions/...
//
// Or directly:
//
//	go run ./cmd/gen-extensions
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type extensionKind struct {
	dir         string
	importRoot  string
	packageName string
	description string
}

var kinds = []extensionKind{
	{
		dir:         "extensions/providers",
		importRoot:  "github.com/yeeth-security/scintx/extensions/providers",
		packageName: "providersall",
		description: "all provider extensions",
	},
	{
		dir:         "extensions/policies",
		importRoot:  "github.com/yeeth-security/scintx/extensions/policies",
		packageName: "policiesall",
		description: "all policy engine extensions",
	},
}

func main() {
	// go:generate runs from the package directory. We walk up to find
	// go.mod so the generator works regardless of where it's invoked.
	cwd, err := os.Getwd()
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-extensions: getwd: %v\n", err)
		os.Exit(1)
	}
	var err2 error
	repoRoot, err2 = findRepoRoot(cwd)
	if err2 != nil {
		fmt.Fprintf(os.Stderr, "gen-extensions: %v\n", err2)
		os.Exit(1)
	}
	for _, k := range kinds {
		k.dir = filepath.Join(repoRoot, k.dir)
		if err := generate(k); err != nil {
			fmt.Fprintf(os.Stderr, "gen-extensions: %s: %v\n", k.dir, err)
			os.Exit(1)
		}
	}
	fmt.Println("gen-extensions: all aggregation files regenerated")
}

var repoRoot string

func findRepoRoot(dir string) (string, error) {
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("could not find go.mod walking up from %s", dir)
		}
		dir = parent
	}
}

func generate(k extensionKind) error {
	if _, err := os.Stat(k.dir); os.IsNotExist(err) {
		return fmt.Errorf("directory does not exist: %s", k.dir)
	}

	// Relative dir for comments (always slash-separated for stable, portable docs).
	relDir, _ := filepath.Rel(repoRoot, k.dir)
	if relDir == "" {
		relDir = k.dir
	}
	relDir = filepath.ToSlash(relDir)

	var pkgs []string
	err := filepath.WalkDir(k.dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() || path == k.dir {
			return nil
		}
		// Skip the "all" aggregation directory itself
		if d.Name() == "all" {
			return nil
		}
		// Skip .gitkeep-only directories
		entries, err := os.ReadDir(path)
		if err != nil {
			return err
		}
		hasGo := false
		for _, e := range entries {
			if strings.HasSuffix(e.Name(), ".go") && !e.IsDir() {
				hasGo = true
				break
			}
		}
		if !hasGo {
			return nil
		}
		rel, err := filepath.Rel(k.dir, path)
		if err != nil {
			return err
		}
		pkg := k.importRoot + "/" + filepath.ToSlash(rel)
		pkgs = append(pkgs, pkg)
		return nil
	})
	if err != nil {
		return err
	}

	sort.Strings(pkgs)

	allDir := filepath.Join(k.dir, "all")
	if err := os.MkdirAll(allDir, 0o755); err != nil {
		return err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by gen-extensions; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "//go:generate go run ../../../cmd/gen-extensions\n\n")
	fmt.Fprintf(&b, "// Package %s imports %s so their init() registrations run.\n", k.packageName, k.description)
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// To add a new extension of this kind:\n")
	fmt.Fprintf(&b, "//  1. Create a directory under %s/<name>/ with a .go file containing init() registration.\n", relDir)
	fmt.Fprintf(&b, "//  2. Run: go generate ./extensions/...\n")
	fmt.Fprintf(&b, "//  3. The new extension is automatically picked up on next build.\n")
	fmt.Fprintf(&b, "package %s\n\n", k.packageName)

	if len(pkgs) == 0 {
		fmt.Fprintf(&b, "// No extensions found in %s. Add one to get started.\n", relDir)
	} else {
		fmt.Fprintf(&b, "import (\n")
		fmt.Fprintf(&b, "\t_ \"github.com/yeeth-security/scintx/api\" // ensure registry is loaded\n")
		for _, p := range pkgs {
			fmt.Fprintf(&b, "\t_ %q\n", p)
		}
		fmt.Fprintf(&b, ")\n")
	}

	allPath := filepath.Join(allDir, "all.go")
	return os.WriteFile(allPath, []byte(b.String()), 0o644)
}
